/* =========================================================================
   Major Advisor — UI copy (i18n). window.MA_COPY[lang]
   Justification templates take the attribute label + the student's own
   rating label, so every reason is literally drawn from their answers.
   ========================================================================= */
window.MA_COPY = {
  ar: {
    dir: "rtl",
    brand: "المرشد الأكاديمي",
    brandSub: "اختر تخصصك بثقة",
    // welcome
    w_badge: "أقل من ٥ دقائق",
    w_title: "لنجد التخصص الجامعي الأنسب لك",
    w_lead: "أجب عن أسئلة قصيرة عن دراستك واهتماماتك ومهاراتك، وسنقترح عليك التخصصات الأنسب — مع شرحٍ واضح لسبب ملاءمة كل تخصص لك.",
    w_reassure: "لا توجد إجابات صحيحة أو خاطئة — هذا تقييم ذاتي يساعدك على الاستكشاف.",
    w_start: "لنبدأ",
    w_lang: "English",
    w_feat1_t: "موجَّه خطوة بخطوة",
    w_feat1_d: "فكرة واحدة في كل شاشة، دون نماذج طويلة.",
    w_feat2_t: "نتائج مُفسَّرة",
    w_feat2_d: "كل توصية مدعومة بأسباب من إجاباتك أنت.",
    w_feat3_t: "أداة دعم للقرار",
    w_feat3_d: "اقتراحات تساعدك، والقرار يبقى لك.",
    // questionnaire
    of: "من",
    section: "القسم",
    sectionA: "الأداء الأكاديمي",
    sectionB: "الاهتمامات",
    sectionC: "المهارات",
    overall: "الإنجاز الكلي",
    next: "التالي",
    back: "السابق",
    skipNote: "يمكنك تخطّي أي سؤال، لكن الإجابة عنه تحسّن دقة النتائج.",
    pickToContinue: "اختر تقييماً للمتابعة",
    // review
    rev_title: "راجِع إجاباتك",
    rev_lead: "تأكّد من أن كل شيء يعكسك بصدق. يمكنك تعديل أي إجابة بنقرة.",
    rev_unanswered: "لم تُجب",
    rev_generate: "أظهر التخصصات المقترحة",
    rev_edit: "تعديل",
    rev_warn: "لديك {n} أسئلة بلا إجابة. يمكنك المتابعة، لكن الإجابة عنها تزيد دقة الترتيب.",
    // processing
    proc_title: "نحلّل ملفك الآن",
    proc_sub: "نطابق إجاباتك مع متطلبات كل تخصص…",
    proc_s1: "نقرأ أداءك الأكاديمي",
    proc_s2: "نوازن اهتماماتك ومهاراتك",
    proc_s3: "نرتّب التخصصات الأنسب لك",
    // results
    res_eyebrow: "بناءً على ما أخبرتنا به",
    res_title: "أفضل ٥ تخصصات تناسبك",
    res_lead: "مرتّبة حسب نسبة التطابق. اضغط أي تخصص لرؤية الأسباب الكاملة. ليست هذه أحكاماً نهائية — بل نقطة انطلاق لحوارك مع مرشدك.",
    res_match: "نسبة التطابق",
    res_why: "لماذا يناسبك",
    res_more: "اعرف المزيد",
    res_seeAll: "عرض كل الأسباب",
    res_retake: "إعادة الاختبار",
    res_adjust: "تعديل الإجابات",
    res_topBadge: "الأنسب لك",
    rank: "المرتبة",
    // detail
    det_match: "نسبة التطابق",
    det_why: "لماذا يناسبك هذا التخصص",
    det_whySub: "كل سبب مأخوذ من إجاباتك أنت.",
    det_grow: "نقطة لتطويرها",
    det_careers: "مسارات مهنية شائعة",
    det_related: "تخصصات قريبة",
    det_compare: "قارن مع التخصص التالي",
    det_compareVs: "مقابل",
    det_back: "العودة إلى النتائج",
    // empty
    empty_title: "لم نجد تطابقاً واضحاً بعد",
    empty_lead: "لا بأس بذلك إطلاقاً. قد تكون إجاباتك متوازنة عبر عدة مجالات. جرّب مراجعة إجاباتك أو تحدّث مع مرشدك الأكاديمي لاستكشاف خياراتك.",
    empty_retake: "مراجعة إجاباتي",
    empty_advisor: "التحدّث مع مرشد",
    // justification templates  → fn(attr, valLabel)
    jt: {
      strengthA: (a, v) => `تقديرك «${v}» في ${a} يدعم هذا التخصص بقوة.`,
      strengthB: (a, v) => `اهتمامك ${a} بمستوى «${v}» يتوافق مع طبيعة هذا التخصص.`,
      strengthC: (a, v) => `مهارة ${a} لديك بمستوى «${v}» مطلوبة كثيراً في هذا المجال.`,
      gapA: (a, v) => `${a} عنصر مهم هنا، وتقديرك الحالي «${v}» — مجال يمكنك تقويته.`,
      gapB: (a, v) => `هذا التخصص يميل إلى ${a}، وقد اخترت «${v}» — أمر يستحق التفكير.`,
      gapC: (a, v) => `${a} مهمة هنا، ومستواك الحالي «${v}» — قابلة للتطوير بالتدريب.`,
    },
    matchOf: (v, a) => `${v} في ${a}`,
  },
  en: {
    dir: "ltr",
    brand: "Major Advisor",
    brandSub: "Choose your major with confidence",
    w_badge: "Under 5 minutes",
    w_title: "Let's find the university major that fits you",
    w_lead: "Answer a few short questions about your studies, interests and skills, and we'll suggest the majors that suit you best — each one explained, so you know exactly why it fits.",
    w_reassure: "There are no right or wrong answers — this is a self-assessment to help you explore.",
    w_start: "Let's begin",
    w_lang: "العربية",
    w_feat1_t: "Guided step by step",
    w_feat1_d: "One idea per screen — never a wall of fields.",
    w_feat2_t: "Explained results",
    w_feat2_d: "Every suggestion is backed by reasons from your own answers.",
    w_feat3_t: "A decision-support tool",
    w_feat3_d: "Suggestions to guide you — the choice stays yours.",
    of: "of",
    section: "Section",
    sectionA: "Academic performance",
    sectionB: "Interests",
    sectionC: "Skills",
    overall: "Overall progress",
    next: "Next",
    back: "Back",
    skipNote: "You can skip any question, but answering improves your results.",
    pickToContinue: "Pick a rating to continue",
    rev_title: "Review your answers",
    rev_lead: "Make sure everything reflects you. Tap any answer to change it.",
    rev_unanswered: "Not answered",
    rev_generate: "Show my recommended majors",
    rev_edit: "Edit",
    rev_warn: "You have {n} unanswered questions. You can continue, but answering improves the ranking.",
    proc_title: "Analysing your profile",
    proc_sub: "Matching your answers to each major's profile…",
    proc_s1: "Reading your academic performance",
    proc_s2: "Weighing your interests and skills",
    proc_s3: "Ranking the majors that fit you best",
    res_eyebrow: "Based on what you told us",
    res_title: "Your top 5 matching majors",
    res_lead: "Ranked by match. Tap any major for the full reasons. These aren't verdicts — they're a starting point for the conversation with your advisor.",
    res_match: "Match",
    res_why: "Why it fits",
    res_more: "Learn more",
    res_seeAll: "See all reasons",
    res_retake: "Retake",
    res_adjust: "Adjust answers",
    res_topBadge: "Best fit for you",
    rank: "Rank",
    det_match: "Match score",
    det_why: "Why this major fits you",
    det_whySub: "Every reason is drawn from your own answers.",
    det_grow: "Something to grow",
    det_careers: "Common career paths",
    det_related: "Related majors",
    det_compare: "Compare with the next major",
    det_compareVs: "vs",
    det_back: "Back to results",
    empty_title: "No clear match — yet",
    empty_lead: "That's completely fine. Your answers may be balanced across several fields. Try reviewing your answers, or talk with your academic advisor to explore your options.",
    empty_retake: "Review my answers",
    empty_advisor: "Talk to an advisor",
    jt: {
      strengthA: (a, v) => `Your ${v} in ${a} strongly supports this major.`,
      strengthB: (a, v) => `Your ${v} ${a} interest aligns with what this major involves.`,
      strengthC: (a, v) => `Your ${v} ${a} skill is in high demand in this field.`,
      gapA: (a, v) => `${a} matters here, and you rated it ${v} — an area you could strengthen.`,
      gapB: (a, v) => `This major leans ${a}, and you chose ${v} — worth a thought.`,
      gapC: (a, v) => `${a} is important here; you're at ${v} now — very trainable.`,
    },
    matchOf: (v, a) => `${v} in ${a}`,
  },
};
